%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/michael/Documents/Github/Reservoir-Computing/Matlab/dde23 with Inputs/Input_sequence.txt
%
% Auto-generated by MATLAB on 16-Jul-2020 15:38:36

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 1);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = "VarName1";
opts.VariableTypes = "double";

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Inputsequence = readtable("/Users/michael/Documents/Github/Reservoir-Computing/Matlab/dde23 with Inputs/Input_sequence.txt", opts);

%% Convert to output type
Inputsequence = table2array(Inputsequence);

%% Clear temporary variables
clear opts
%% Meat and Potatoes

[sox, soy] = dde23_Jt_Hayes(0.2,Inputsequence);

plot(sox,soy);



